#!/usr/bin/env node
var exec = require('child_process').exec;

var branch = exec("git branch | grep '*'",
  function (err, data) {
    var name = data.replace('* ','').replace('\n','');

    jshint();
    if ('master' === name) {
      test();
    }
  }
);

function test() {
  exec('cd client; gulp test', function(err, data) {
    if (data.match(/FAILED/)) {
      console.error('Tests failed! Run `npm test!');
      process.exit(1);
    } else {
      process.exit(0);
    }
  });
}

function jshint() {
  exec('cd client; gulp lint', function (err, data) {
    if (data.match(/problem/)) {
      console.error('Lint failed! Run `gulp lint`!');
      process.exit(1);
    } else {
      process.exit(0);
    }
  });
}
